### ISSUE TITLE
Implement meter "wake up" 

### ISSUE THREAD

**Issue by weidi** [BMOD89/esphome_compontens#1]
Hi, 

i have a meter that needs to get waked up using a pullsequence. This is working in tasmota using this line

+1,13,o,0,300,STROM,15,32,**2F3F210D0A**,063030300D0A

I´d love to see this implemented with your esphome component but i have no clue on how to implement this.

**Comment by terveer** [comment]
```
interval:
  - interval: 300sec
    then:
      #- uart.write: [0x2F, 0x3F, 0x21, 0x0D, 0x0A]
      - uart.write: [0x2F, 0x32, 0x21, 0x0D, 0x0A]
```
 
For my Elster smart meter I use the interval like this. At 300 baud it can take 5 minutes until every single data line shows up.
